# mainapp/add_vue_questions.py
from mainapp.models import Question


def add_vue_questions():
    questions = [
        # --- Basics (1–15) ---
        Question(
            category="Vue",
            text="What is Vue.js primarily used for?",
            option1="Server-side rendering",
            option2="Building user interfaces",
            option3="Database management",
            option4="Mobile app development",
            answer="Building user interfaces",
        ),
        Question(
            category="Vue",
            text="Who created Vue.js?",
            option1="Evan You",
            option2="Jordan Walke",
            option3="Brendan Eich",
            option4="Yehuda Katz",
            answer="Evan You",
        ),
        Question(
            category="Vue",
            text="Which directive is used for conditional rendering in Vue?",
            option1="v-if",
            option2="v-for",
            option3="v-bind",
            option4="v-model",
            answer="v-if",
        ),
        Question(
            category="Vue",
            text="Which directive is used for looping through lists in Vue?",
            option1="v-if",
            option2="v-for",
            option3="v-show",
            option4="v-model",
            answer="v-for",
        ),
        Question(
            category="Vue",
            text="What is the correct way to bind HTML attributes dynamically?",
            option1=":attribute='value'",
            option2="bind-attribute='value'",
            option3="data-attribute='value'",
            option4="v-attr='value'",
            answer=":attribute='value'",
        ),
        Question(
            category="Vue",
            text="Which directive is used for two-way data binding?",
            option1="v-bind",
            option2="v-model",
            option3="v-for",
            option4="v-on",
            answer="v-model",
        ),
        Question(
            category="Vue",
            text="Which lifecycle hook is called when a Vue instance is created?",
            option1="mounted",
            option2="created",
            option3="updated",
            option4="beforeDestroy",
            answer="created",
        ),
        Question(
            category="Vue",
            text="What does the 'mounted' lifecycle hook do?",
            option1="Executes before component creation",
            option2="Executes after the DOM has been inserted",
            option3="Executes when the app is destroyed",
            option4="Executes during compilation",
            answer="Executes after the DOM has been inserted",
        ),
        Question(
            category="Vue",
            text="What is the default file extension for Vue single-file components?",
            option1=".vue",
            option2=".vjs",
            option3=".component",
            option4=".jsx",
            answer=".vue",
        ),
        Question(
            category="Vue",
            text="Which keyword is used to define a Vue component?",
            option1="Vue.component",
            option2="Vue.create",
            option3="Vue.module",
            option4="Vue.make",
            answer="Vue.component",
        ),
        # --- Intermediate (16–40) ---
        Question(
            category="Vue",
            text="Which Vue directive is used for event handling?",
            option1="v-for",
            option2="v-bind",
            option3="v-on",
            option4="v-show",
            answer="v-on",
        ),
        Question(
            category="Vue",
            text="What is the shorthand for v-bind?",
            option1=":",
            option2="@",
            option3="$",
            option4="#",
            answer=":",
        ),
        Question(
            category="Vue",
            text="What is the shorthand for v-on?",
            option1=":",
            option2="@",
            option3="$",
            option4="!",
            answer="@",
        ),
        Question(
            category="Vue",
            text="Which Vue.js feature allows passing data from parent to child components?",
            option1="props",
            option2="data",
            option3="methods",
            option4="emit",
            answer="props",
        ),
        Question(
            category="Vue",
            text="How do child components send data back to parent?",
            option1="props",
            option2="$emit",
            option3="v-bind",
            option4="v-model",
            answer="$emit",
        ),
        Question(
            category="Vue",
            text="Which Vue directive is used for toggling element visibility without removing it from the DOM?",
            option1="v-if",
            option2="v-show",
            option3="v-for",
            option4="v-on",
            answer="v-show",
        ),
        Question(
            category="Vue",
            text="What is Vue Router used for?",
            option1="State management",
            option2="Routing between pages",
            option3="Styling components",
            option4="Managing APIs",
            answer="Routing between pages",
        ),
        Question(
            category="Vue",
            text="Which package is commonly used for state management in Vue?",
            option1="Redux",
            option2="MobX",
            option3="Vuex",
            option4="Pinia",
            answer="Vuex",
        ),
        Question(
            category="Vue",
            text="What is the replacement of Vuex in Vue 3?",
            option1="Context API",
            option2="Pinia",
            option3="NgRx",
            option4="Recoil",
            answer="Pinia",
        ),
        Question(
            category="Vue",
            text="Which Vue directive is used to render raw HTML?",
            option1="v-html",
            option2="v-text",
            option3="v-if",
            option4="v-bind",
            answer="v-html",
        ),
        Question(
            category="Vue",
            text="How do you apply conditional classes in Vue?",
            option1=":class",
            option2="v-if-class",
            option3="v-class",
            option4="class-bind",
            answer=":class",
        ),
        Question(
            category="Vue",
            text="What is the Composition API introduced in Vue 3?",
            option1="A new way to write reusable logic",
            option2="A new router feature",
            option3="A state management tool",
            option4="A template engine",
            answer="A new way to write reusable logic",
        ),
        Question(
            category="Vue",
            text="Which hook in Vue 3 replaces mixins?",
            option1="setup()",
            option2="mounted()",
            option3="computed()",
            option4="watch()",
            answer="setup()",
        ),
        Question(
            category="Vue",
            text="How do you declare reactive state in Vue 3?",
            option1="data()",
            option2="ref() and reactive()",
            option3="props",
            option4="store()",
            answer="ref() and reactive()",
        ),
        Question(
            category="Vue",
            text="What does Vue’s 'teleport' feature do?",
            option1="Optimizes rendering",
            option2="Moves an element to a different DOM location",
            option3="Improves SEO",
            option4="Handles routing",
            answer="Moves an element to a different DOM location",
        ),
        # --- Advanced (41–60) ---
        Question(
            category="Vue",
            text="What does Vue’s 'nextTick()' method do?",
            option1="Executes code after DOM updates",
            option2="Delays execution for 1 second",
            option3="Performs API requests",
            option4="Executes before render",
            answer="Executes code after DOM updates",
        ),
        Question(
            category="Vue",
            text="Which function is used to create a global state store in Pinia?",
            option1="createStore",
            option2="defineStore",
            option3="makeStore",
            option4="initStore",
            answer="defineStore",
        ),
        Question(
            category="Vue",
            text="Which tool is used to debug Vue applications?",
            option1="React DevTools",
            option2="Vue DevTools",
            option3="Redux DevTools",
            option4="Chrome Inspector",
            answer="Vue DevTools",
        ),
        Question(
            category="Vue",
            text="What is a computed property in Vue?",
            option1="A method that always re-runs",
            option2="A cached property that updates when dependencies change",
            option3="A global variable",
            option4="A state from Vuex",
            answer="A cached property that updates when dependencies change",
        ),
        Question(
            category="Vue",
            text="Which directive is used to bind inline styles?",
            option1=":style",
            option2="v-style",
            option3="v-css",
            option4="style-bind",
            answer=":style",
        ),
        Question(
            category="Vue",
            text="How do you define watchers in Vue?",
            option1="Using watch property or watch() in Composition API",
            option2="Using v-on",
            option3="Using computed properties only",
            option4="Using Vuex",
            answer="Using watch property or watch() in Composition API",
        ),
        Question(
            category="Vue",
            text="Which feature of Vue helps to improve performance in lists?",
            option1="v-show",
            option2="key attribute",
            option3="v-if",
            option4="v-once",
            answer="key attribute",
        ),
        Question(
            category="Vue",
            text="What is Vue CLI used for?",
            option1="Generating Vue projects quickly",
            option2="Running database queries",
            option3="Deploying to servers",
            option4="Debugging APIs",
            answer="Generating Vue projects quickly",
        ),
        Question(
            category="Vue",
            text="What is Nuxt.js?",
            option1="A Vue framework for server-side rendering",
            option2="A state management library",
            option3="A CSS framework",
            option4="A debugging tool",
            answer="A Vue framework for server-side rendering",
        ),
        Question(
            category="Vue",
            text="Which function is used in Vue 3 to share logic between components?",
            option1="mixins",
            option2="composables",
            option3="services",
            option4="props",
            answer="composables",
        ),
    ]

    Question.objects.bulk_create(questions, ignore_conflicts=True)
    print("✅ 60 Vue.js questions added successfully!")
