from mainapp.models import Question


def add_questions():
    questions = [
        Question(
            text="What is React primarily used for?",
            option1="Database management",
            option2="Building user interfaces",
            option3="Server-side scripting",
            option4="Operating system design",
            answer="Building user interfaces",
            category="React",
        ),
        Question(
            text="Which method is used to update state in a functional component?",
            option1="this.setState",
            option2="useState hook",
            option3="updateState()",
            option4="stateChange()",
            answer="useState hook",
            category="React",
        ),
        Question(
            text="What does JSX stand for?",
            option1="Java Syntax Extension",
            option2="JavaScript XML",
            option3="Java Standard Expression",
            option4="JSON Extended",
            answer="JavaScript XML",
            category="React",
        ),
        Question(
            text="Which hook is used to perform side effects in functional components?",
            option1="useEffect",
            option2="useState",
            option3="useContext",
            option4="useReducer",
            answer="useEffect",
            category="React",
        ),
        Question(
            text="What is the virtual DOM?",
            option1="A copy of the actual DOM kept in memory",
            option2="A database schema",
            option3="A browser API for styling",
            option4="A JavaScript compiler",
            answer="A copy of the actual DOM kept in memory",
            category="React",
        ),
        Question(
            text="Which command creates a new React app?",
            option1="npx create-react-app myApp",
            option2="npm new react myApp",
            option3="npm start react myApp",
            option4="node create react myApp",
            answer="npx create-react-app myApp",
            category="React",
        ),
        Question(
            text="Which hook is used for managing global state?",
            option1="useRef",
            option2="useEffect",
            option3="useContext",
            option4="useMemo",
            answer="useContext",
            category="React",
        ),
        Question(
            text="What is the purpose of React.Fragment?",
            option1="To wrap multiple elements without adding an extra DOM node",
            option2="To handle async data",
            option3="To manage state",
            option4="To optimize rendering",
            answer="To wrap multiple elements without adding an extra DOM node",
            category="React",
        ),
        Question(
            text="What is React.StrictMode used for?",
            option1="To enforce best practices and highlight potential problems",
            option2="To run React in production mode",
            option3="To manage API requests",
            option4="To style components",
            answer="To enforce best practices and highlight potential problems",
            category="React",
        ),
        Question(
            text="Which prop is required when rendering lists in React?",
            option1="id",
            option2="class",
            option3="key",
            option4="ref",
            answer="key",
            category="React",
        ),
        Question(
            category="React",
            text="What is React primarily used for?",
            option1="Building user interfaces",
            option2="Managing databases",
            option3="Server-side scripting",
            option4="File storage",
            answer="Building user interfaces",
        ),
        Question(
            category="React",
            text="Which company developed React?",
            option1="Google",
            option2="Facebook",
            option3="Microsoft",
            option4="Twitter",
            answer="Facebook",
        ),
        Question(
            category="React",
            text="What is JSX?",
            option1="A template language for HTML",
            option2="A syntax extension that looks like HTML but is JavaScript",
            option3="A CSS preprocessor",
            option4="A database query language",
            answer="A syntax extension that looks like HTML but is JavaScript",
        ),
        Question(
            category="React",
            text="Which hook is used to handle state in functional components?",
            option1="useEffect",
            option2="useState",
            option3="useReducer",
            option4="useRef",
            answer="useState",
        ),
        Question(
            category="React",
            text="What is the default port for React development server?",
            option1="3000",
            option2="8000",
            option3="5000",
            option4="4200",
            answer="3000",
        ),
        Question(
            category="React",
            text="Which hook is used for side effects?",
            option1="useEffect",
            option2="useState",
            option3="useMemo",
            option4="useRef",
            answer="useEffect",
        ),
        Question(
            category="React",
            text="What is the purpose of ReactDOM?",
            option1="To manipulate the virtual DOM",
            option2="To connect React with the actual DOM",
            option3="To style React components",
            option4="To manage state",
            answer="To connect React with the actual DOM",
        ),
        Question(
            category="React",
            text="Which method is used to update state in class components?",
            option1="this.setState()",
            option2="this.updateState()",
            option3="this.changeState()",
            option4="this.state()",
            answer="this.setState()",
        ),
        Question(
            category="React",
            text="What does the Virtual DOM improve?",
            option1="Database performance",
            option2="UI rendering performance",
            option3="Backend APIs",
            option4="File storage",
            answer="UI rendering performance",
        ),
        Question(
            category="React",
            text="Which hook is used to reference DOM elements directly?",
            option1="useState",
            option2="useEffect",
            option3="useRef",
            option4="useMemo",
            answer="useRef",
        ),
        Question(
            category="React",
            text="What is prop drilling?",
            option1="Passing props deeply through multiple components unnecessarily",
            option2="Updating props in parent component",
            option3="Fetching props from API",
            option4="Storing props in Redux",
            answer="Passing props deeply through multiple components unnecessarily",
        ),
        Question(
            category="React",
            text="Which hook is used to optimize expensive calculations?",
            option1="useEffect",
            option2="useMemo",
            option3="useState",
            option4="useContext",
            answer="useMemo",
        ),
        Question(
            category="React",
            text="React is ________",
            option1="A framework",
            option2="A library",
            option3="A programming language",
            option4="An operating system",
            answer="A library",
        ),
        Question(
            category="React",
            text="What is React Fiber?",
            option1="A new CSS library",
            option2="A new reconciliation algorithm for React 16+",
            option3="A debugging tool",
            option4="A testing framework",
            answer="A new reconciliation algorithm for React 16+",
        ),
        Question(
            category="React",
            text="Which hook provides context in functional components?",
            option1="useState",
            option2="useEffect",
            option3="useContext",
            option4="useReducer",
            answer="useContext",
        ),
        Question(
            category="React",
            text="What is the purpose of keys in React lists?",
            option1="They style the list",
            option2="They help React identify which items changed",
            option3="They are used for authentication",
            option4="They improve SEO",
            answer="They help React identify which items changed",
        ),
        Question(
            category="React",
            text="What is the default parent component of every React app?",
            option1="<View>",
            option2="<div>",
            option3="<App>",
            option4="<React.StrictMode>",
            answer="<React.StrictMode>",
        ),
        # 20 more (total 30) ...
    ]


    Question.objects.bulk_create(questions, ignore_conflicts=True)
    print("✅ 30 React questions added successfully!")
